### ISSUE TITLE
TypeError: init() missing 2 required positional arguments: 'format' and 'fields'

### ISSUE THREAD

**Issue by Yaoying-1** [PYangLab/SnapCCESS#1]
Hello, when I tried to reproduce the "an_example_of_generate_embedding_using_SnapCCESS_python_version" code, I encountered an error:
File "/home/september/PycharmProjects/SnapCCESS/snapccess-py/snapccess/loaddata.py", line 58, in
train_transformed_dataset = TabularDataset(train_data)
TypeError: init() missing 2 required positional arguments: 'format' and 'fields'
Previously, you mentioned the import statement was from snapccess.util import setup_seed, TabularDataset. However, I couldn't find the TabularDataset class in the util.py file. I am referring to the TabularDataset class from torchtext.data.dataset. Can you please help me solve this issue? Or can you provide the complete code? Thank you very much!

**Comment by yulijia** [comment]
Hi @Yaoying-1 

Thank you for your feedback.
I updated the python notebook, please check the latest version of example. `TabularDataset` is a useless function, I already removed it in the notebook and package.
